FROM golang:1.21-alpine

WORKDIR /app

# Install wait-for-it script
RUN apk add --no-cache bash

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Set environment variables
ENV DB_HOST=db
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_NAME=personal_website
ENV DB_SSLMODE=disable
ENV PORT=8080

CMD ["go", "run", "main.go"] 